spring:
  application:
    name: content-center
  main:
      allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 106.13.81.68:8848
server:
  port: 8082

ahas.namespace: default
project.name: content-center
ahas.license: 8f31af8dc3204714b62916c5301e1f9e